Calling main()
Entering try
Creating first c
Creating second c
Caught: Undefined variable: x
Returning from main
Back from main()
